# Generated by Django 2.1.7 on 2019-03-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_post_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='static/img/'),
            preserve_default=False,
        ),
    ]
